version: "3"
services:
  client:
    container_name: client
    build:
      context: image.client-head
    command: /wait-for-it.sh master:389 -t 120 -- /usr/local/sbin/sssd -i
    volumes:
      - ./client/sssd.conf:/usr/local/etc/sssd/sssd.conf
    privileged: true
